### ISSUE TITLE
Allow removing a component

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rustwide#19]
If a component is not available on the latest nightly, rustup will refuse to update. The workaround is to first remove the component from the toolchain, but `rustwide` doesn't expose this in the `Toolchain` API.

See also https://github.com/rust-lang/docs.rs/issues/357#issuecomment-606252725

**Comment by jyn514** [comment]
As per https://github.com/rust-lang/docs.rs/issues/357#issuecomment-606622489 I no longer need this, but it would be a nice addition to the API all the same.

**Comment by kellda** [comment]
Looks quite easy, I'd like to implement this. Is there also tests or documentation to update ?
