### ISSUE TITLE
failed to create directory "/opt/rustwide/cargo-home/registry/index/github.com-1ecc6299db9ec823"

### ISSUE THREAD

**Issue by Ren-ZY** [rust-lang/rustwide#68]
"docker" "start" cannot create directory in "/opt"
Caused by : Read-only file system

**Comment by Ren-ZY** [comment]
Ok, Just change the "READONLY" to "READWRITE"

**Comment by wyf18** [comment]
> Ok, Just change the "READONLY" to "READWRITE"

I have the same problem, can you tell me how to solve it？
by the way, I met it in [Qrates](https://github.com/rust-corpus/qrates)，a tool which uses the rustwide library
